apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: demo2
  labels:
    app: guestbook
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx


