apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    tier: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app1
  template:
    metadata:
      labels:
        tier: app1
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cip
spec:
  selector:
    tier: app1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
