apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    tier: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app1
  template:
    metadata:
      labels:
        tier: app1
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
