apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  URL: example.com
---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - configMapRef:
            name: test-cm
